### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by Atcold** [imodpasteur/lutorpy#25] opened 2016-10-19 19:19 UTC
# Installation

``` bash
pip install lutorpy
```

won't install unless you

``` bash
export CC=gcc-6 
export CXX=g++-6
```

This is because

``` bash
 clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLUA_COMPAT_ALL -I/Users/atcold/torch/install/include -I/Users/atcold/torch/install/include/TH -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/lo
cal/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lutorpy/_lupa.c -o build/temp.macosx-10.11-x86_64-2.7/lutorpy/_lupa.o -std=c++0x -Wno-unused-func
tion -Wno-unreachable-code -Wno-strict-prototypes
  error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
  error: command 'clang' failed with exit status 1
```
# Importing

After having it installed, it won't import in `python`, and produces the following error

``` python
In [1]: import lutorpy as lua
---------------------------------------------------------------------------
LuaError                                  Traceback (most recent call last)
<ipython-input-1-ab626d710fb4> in <module>()
----> 1 import lutorpy as lua

/usr/local/lib/python2.7/site-packages/lutorpy/__init__.pyc in <module>()
     72     return luaRuntime
     73
---> 74 LuaRuntime()
     75
     76 class global_injector:

/usr/local/lib/python2.7/site-packages/lutorpy/__init__.pyc in LuaRuntime(*args, **kwargs)
     69     if not 'zero_based_index' in kwargs:
     70         kwargs['zero_based_index']=True
---> 71     luaRuntime = lutorpy._lupa.LuaRuntime(*args, **kwargs)
     72     return luaRuntime
     73

lutorpy/_lupa.pyx in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)()

LuaError: Failed to initialise Lua runtime
```

Alright, tried to `import lupa` and I get an `ImportError: No module named lupa`. So, I guess there are missing dependencies in the `pip` installation procedure.

``` bash
pip install lupa
```

Now `lupa` `import`s just fine, but `import`ing `lutorpy as lua` gives `Segmentation fault: 11`.
More fun. Different bug while doing the same thing.

``` python
In [1]: import lupa

In [2]: import lutorpy
PANIC: unprotected error in call to Lua API (attempt to index a nil value)
Abort trap: 6
```

And even more variety

``` python
In [1]: import lutorpy
---------------------------------------------------------------------------
LuaError                                  Traceback (most recent call last)
<ipython-input-1-db94a7dcb3df> in <module>()
----> 1 import lutorpy

/usr/local/lib/python2.7/site-packages/lutorpy/__init__.pyc in <module>()
     72     return luaRuntime
     73
---> 74 LuaRuntime()
     75
     76 class global_injector:

/usr/local/lib/python2.7/site-packages/lutorpy/__init__.pyc in LuaRuntime(*args, **kwargs)
     69     if not 'zero_based_index' in kwargs:
     70         kwargs['zero_based_index']=True
---> 71     luaRuntime = lutorpy._lupa.LuaRuntime(*args, **kwargs)
     72     return luaRuntime
     73

lutorpy/_lupa.pyx in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)()

LuaError: Failed to initialise Lua runtime

In [2]: import lutorpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-db94a7dcb3df> in <module>()
----> 1 import lutorpy

/usr/local/lib/python2.7/site-packages/lutorpy/__init__.py in <module>()
     10 assert not os.path.exists('./lutorpy/_lupa.pyx'), 'PLEASE DO NOT IMPORT LUTORPY FROM SOURCE CODE FOLDER.'
     11
---> 12 from lutorpy import torch_path
     13
     14 TorchInstallPath = torch_path.__torch_path__

ImportError: cannot import name torch_path
```

**Comment by oeway** [comment] 2016-10-23 16:55
duplicate of #13

**Closed as completed by oeway** 2016-10-23 16:55 UTC

**Comment by Atcold** [comment] 2016-10-26 20:05
@oeway, this issue is unrelated from #13.
Here I am using python2. In #13 python3 is used instead.
Here I can install with `pip` just fine, in #13 the code has to be installed from source.
OK, I see now your reply https://github.com/imodpasteur/lutorpy/issues/13#issuecomment-235761624.

**Comment by oeway** [comment] 2016-10-26 20:24
Hi @Atcold , 
It is related because we haven't figure out how to compile lutorpy(or lupa) with the torch luajit on OSX. You can check my comments in #13, I was actually trying with python2.7. 

I will give another try and let you know if it works.

**Comment by oeway** [comment] 2016-10-26 20:50
@Atcold 
I haven't figure out how to solve it, I have some trouble to load library. 

Could you please try to reinstall torch with Lua 5.2 instead of LuaJIT?
You can find how to do it here: http://torch.ch/docs/getting-started.html
You need to remove lutorpy and torch completely, if you installed lua with homebrew for example, you should also remove it.
Then you install torch with Lua 5.2, followed by lutorpy with pip.
Then try to import lutorpy and use 'nn' module for example.
Thank you.

**Comment by Atcold** [comment] 2016-10-28 15:32
OK, thank you for getting back to me.
I'll give it a try. But on my Ubuntu box everything works just fine with LuaJIT.
I'm wondering where I specify which torch installation to use for _lupa_ and _lutorpy_. Is there a config file somewhere?
